In [1]:
import numpy as np
from statsmodels.robust.scale import huber
from statsmodels.tsa.stattools import adfuller

In [2]:
import pandas as pd
import time,datetime

In [3]:
from statsmodels.robust.scale import qn,qn_scale

In [4]:
# Mean and standard deviation to generate normal random variates
mean, std_dev = 0, 2
sample_size = 125
np.random.seed(42)
x = np.random.normal(mean, std_dev, sample_size)
# Appends a couple of outliers
#x = np.append(x, (50, 100))

In [5]:
x

array([ 0.99342831, -0.2765286 ,  1.29537708,  3.04605971, -0.46830675,
       -0.46827391,  3.15842563,  1.53486946, -0.93894877,  1.08512009,
       -0.92683539, -0.93145951,  0.48392454, -3.82656049, -3.44983567,
       -1.12457506, -2.02566224,  0.62849467, -1.81604815, -2.8246074 ,
        2.93129754, -0.4515526 ,  0.13505641, -2.84949637, -1.08876545,
        0.22184518, -2.30198715,  0.75139604, -1.20127738, -0.5833875 ,
       -1.20341322,  3.70455637, -0.02699445, -2.11542186,  1.64508982,
       -2.4416873 ,  0.41772719, -3.91934025, -2.6563721 ,  0.39372247,
        1.47693316,  0.34273656, -0.23129656, -0.60220739, -2.95704398,
       -1.43968842, -0.92127754,  2.11424445,  0.68723658, -3.52608031,
        0.64816794, -0.77016456, -1.353844  ,  1.22335258,  2.06199904,
        1.86256024, -1.67843505, -0.61842475,  0.66252686,  1.95109025,
       -0.95834848, -0.37131795, -2.21266995, -2.39241325,  1.62505164,
        2.71248006, -0.14402024,  2.0070658 ,  0.72327205, -1.29

In [20]:
f = adfuller(x)

In [23]:
f

(-11.424779824371464,
 6.736995964954299e-21,
 0,
 124,
 {'1%': -3.484219653271961,
  '5%': -2.885145235641637,
  '10%': -2.579359138917794},
 457.0457307352889)

In [24]:
type(f)

tuple

In [6]:
print (np.mean(x), np.std(x))

5.2527628543368685 20.945734041764215


In [9]:
y = huber(x)

In [10]:
y

(array(-0.03323791), array(2.36742171))

In [11]:
y[1].item(0)

2.367421713671407

In [12]:
print(qn_scale(x))

2.4281939407751443


In [10]:
len(x)*y.item(0)

-0.8974235880007292

In [4]:
dfd =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
dfd['date'] = pd.to_datetime(dfd['date'])

In [23]:
x1= dfd.loc[dfd['name'] == 'BartonLLC']

In [24]:
x1 = x1.set_index('date')

In [25]:
x2 = x1.between_time('04:00', '10:00')                     

In [26]:
x2.head()

Unnamed: 0  account number       name       sku  \
date                                                                   
2014-01-01 04:21:00           0          740150  BartonLLC  B1-20000   
2014-01-01 04:21:30           1          714466  BartonLLC  S2-77896   
2014-01-01 05:22:00           2          218895  BartonLLC  B1-69924   
2014-01-01 06:22:30           3          740150  BartonLLC  B1-69924   

                     quantity  unit price  ext price  
date                                                  
2014-01-01 04:21:00        39       86.69    3380.91  
2014-01-01 04:21:30        -1       63.16     -63.16  
2014-01-01 05:22:00        23       90.70    2086.10  
2014-01-01 06:22:30        41       21.05     863.05

In [27]:
type(x2)

pandas.core.frame.DataFrame

In [29]:
if not x2.empty:
    print("fuck")

fuck


In [13]:
x1.groupby(pd.Grouper( freq='D'))['unit price'].agg('mean')

date
2014-01-01    58.36440
2014-01-02    50.58125
Freq: D, Name: unit price, dtype: float64

In [29]:
y = dfd.groupby(pd.Grouper(key='date', freq='D'))['unit price'].apply(lambda x : x.to_numpy())

In [30]:
type(y)

pandas.core.series.Series

In [32]:
ya = y.to_numpy()

In [33]:
ya[0]

array([86.69, 63.16, 90.7 , 21.05, 83.21, 87.63, 31.1 , 33.25, 84.09,
       81.92, 67.74, 20.26, 61.31, 12.44, 71.56, 71.51, 72.75, 16.23,
       94.3 , 31.18, 96.95, 50.29, 52.41, 16.97, 60.41])

In [34]:
len(dfd['date'])

41

In [41]:
np.abs(dfd['quantity'].max())

48

In [38]:
na = np.arange(0, dfd['quantity'].max() + 5 , 5)

In [39]:
na

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [7]:
df1 =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
df1['date'] = pd.to_datetime(df1['date'])

In [131]:
df1['days'] = df1['date'].dt.date
df1['days'] = pd.to_datetime(df1['days'])

In [132]:
df1.head(5)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0           0          740150  BartonLLC  B1-20000        39       86.69   
1           1          714466  BartonLLC  S2-77896        -1       63.16   
2           2          218895  BartonLLC  B1-69924        23       90.70   
3           3          740150  BartonLLC  B1-69924        41       21.05   
4           4          412290   Kassulke  S2-34077         6       83.21   

   ext price                date       days  
0    3380.91 2014-01-01 04:21:00 2014-01-01  
1     -63.16 2014-01-01 04:21:30 2014-01-01  
2    2086.10 2014-01-01 05:22:00 2014-01-01  
3     863.05 2014-01-01 06:22:30 2014-01-01  
4     499.26                 NaT        NaT

In [8]:
y1 = df1.groupby(pd.Grouper(key='date', freq='2H'))['unit price'].agg(sum)

In [9]:
type(y1)

pandas.core.series.Series

In [10]:
y1

date
2014-01-01 04:00:00    240.55
2014-01-01 06:00:00    191.89
2014-01-01 08:00:00    230.36
2014-01-01 10:00:00     88.00
2014-01-01 12:00:00    216.82
2014-01-01 14:00:00    183.28
2014-01-01 16:00:00    308.21
2014-01-01 18:00:00      0.00
2014-01-01 20:00:00      0.00
2014-01-01 22:00:00      0.00
2014-01-02 00:00:00      0.00
2014-01-02 02:00:00      0.00
2014-01-02 04:00:00      0.00
2014-01-02 06:00:00    180.72
2014-01-02 08:00:00      0.00
2014-01-02 10:00:00    218.07
2014-01-02 12:00:00     55.40
2014-01-02 14:00:00     43.40
2014-01-02 16:00:00      0.00
2014-01-02 18:00:00     73.04
2014-01-02 20:00:00    169.31
2014-01-02 22:00:00     69.36
Freq: 2H, Name: unit price, dtype: float64

In [21]:
y2 = y1.resample('D').apply(lambda x : x.to_numpy())

In [22]:
type(y2)

pandas.core.series.Series

In [23]:
y2

date
2014-01-01    [240.55, 191.89, 230.36, 88.0, 216.82, 183.28,...
2014-01-02    [0.0, 0.0, 0.0, 180.72, 0.0, 218.0700000000000...
Freq: D, Name: unit price, dtype: object

In [20]:
y2.shape

(2,)

In [233]:
y2[0] = np.pad(y2[0], (2, 0), 'constant')

In [234]:
len(y2[0])

12

In [235]:
y2[0].size

12

In [210]:
df2.head(5)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0           0          740150  BartonLLC  B1-20000        39       86.69   
1           1          714466  BartonLLC  S2-77896        -1       63.16   
2           2          218895  BartonLLC  B1-69924        23       90.70   
3           3          307599  BartonLLC  B1-69924        41       21.05   
4           4          412290   Kassulke  S2-34077         6       83.21   

   ext price                date  
0    3380.91 2014-01-01 04:21:00  
1     -63.16 2014-01-01 04:21:30  
2    2086.10 2014-01-01 05:22:00  
3     863.05 2014-01-01 06:22:30  
4     499.26 2014-01-01 07:23:00

In [154]:
x  = pd.Timestamp(df2['date'][0])

In [183]:
idx = len(df2['date'])

In [184]:
idx

41

In [155]:
x

Timestamp('2014-01-01 04:21:00')

In [178]:
y  = pd.Timestamp(df2['date'][idx-1])

In [179]:
y

Timestamp('2014-01-02 23:41:00')

In [180]:
z = (y-x)

In [185]:
z1 = (y-x).to_pytimedelta().days

In [186]:
z1

1

In [236]:
z = np.stack(y2, axis=0)

In [237]:
z

array([[  0.  ,   0.  , 240.55, 191.89, 230.36,  88.  , 216.82, 183.28,
        308.21,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  , 180.72,   0.  , 218.07,  55.4 ,  43.4 ,
          0.  ,  73.04, 169.31,  69.36]])

In [110]:
z.shape

(8,)

In [111]:
z1 = z[:,3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [109]:
z1

NameError: name 'z1' is not defined

In [241]:
np.mean(z1)

186.305

In [242]:
np.std(z1)

5.584999999999994

In [7]:
df1 =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
df1['date'] = pd.to_datetime(df1['date'])

In [8]:
df1.head(5)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0           0          740150  BartonLLC  B1-20000        39       86.69   
1           1          714466  BartonLLC  S2-77896        -1       63.16   
2           2          218895  BartonLLC  B1-69924        23       90.70   
3           3          740150  BartonLLC  B1-69924        41       21.05   
4           4          412290   Kassulke  S2-34077         6       83.21   

   ext price                date  
0    3380.91 2014-01-01 04:21:00  
1     -63.16 2014-01-01 04:21:30  
2    2086.10 2014-01-01 05:22:00  
3     863.05 2014-01-01 06:22:30  
4     499.26 2014-01-01 07:23:00

In [9]:
df2 = df1.loc[df1['name'] == 'BartonLLC']

In [10]:
df2.head(10)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0            0          740150  BartonLLC  B1-20000        39       86.69   
1            1          714466  BartonLLC  S2-77896        -1       63.16   
2            2          218895  BartonLLC  B1-69924        23       90.70   
3            3          740150  BartonLLC  B1-69924        41       21.05   
29          29          729833  BartonLLC  B1-86481         6       81.79   
30          30          642753  BartonLLC  B1-86481         4       87.18   
31          31          714466  BartonLLC  B1-86481        32       19.56   
32          32          737550  BartonLLC  B1-86481        20       29.54   
33          33          218895  BartonLLC  B1-86481         3       22.36   
34          34          307599  BartonLLC  B1-86481        35       33.04   

    ext price                date  
0     3380.91 2014-01-01 04:21:00  
1      -63.16 2014-01-01 04:21:30  
2     2086.10 2014-01-01 05:22:00  
3      863.05 2014-01-01 06:22:30  
29     490.74 2014-01-02 10:35:30  
30     348.72 2014-01-02 10:36:00  
31     625.92 2014-01-02 10:36:30  
32     590.80 2014-01-02 10:37:00  
33      67.08 2014-01-02 13:37:30  
34    1156.40 2014-01-02 13:38:00

In [11]:
y = df2.groupby('account number')['account number'].agg('count')

In [12]:
y

account number
218895    3
307599    1
527099    1
642753    1
714466    2
729833    1
737550    1
740150    2
Name: account number, dtype: int64

In [59]:
type(y)

pandas.core.series.Series

In [60]:
y.to_numpy()

array([3, 1, 1, 1, 2, 1, 1, 2])

In [63]:
z = df2.groupby('account number')['account number'].agg('nunique').to_numpy()

In [64]:
z

array([1, 1, 1, 1, 1, 1, 1, 1])

In [68]:
 np.zeros(shape=2, dtype=float)

array([0., 0.])

In [86]:
df1['date'] = pd.to_datetime(df1['date'])

In [99]:
df1.head()

Unnamed: 0  account number       name       sku  \
date                                                                   
2014-01-01 04:21:00           0          740150  BartonLLC  B1-20000   
2014-01-01 04:21:30           1          714466  BartonLLC  S2-77896   
2014-01-01 05:22:00           2          218895  BartonLLC  B1-69924   
2014-01-01 06:22:30           3          740150  BartonLLC  B1-69924   
2014-01-01 07:23:00           4          412290   Kassulke  S2-34077   

                     quantity  unit price  ext price  
date                                                  
2014-01-01 04:21:00        39       86.69    3380.91  
2014-01-01 04:21:30        -1       63.16     -63.16  
2014-01-01 05:22:00        23       90.70    2086.10  
2014-01-01 06:22:30        41       21.05     863.05  
2014-01-01 07:23:00         6       83.21     499.26

In [101]:
mask = df1.between_time('04:00:00', '07:00:00')

In [105]:
mask

Unnamed: 0  account number       name       sku  \
date                                                                   
2014-01-01 04:21:00           0          740150  BartonLLC  B1-20000   
2014-01-01 04:21:30           1          714466  BartonLLC  S2-77896   
2014-01-01 05:22:00           2          218895  BartonLLC  B1-69924   
2014-01-01 06:22:30           3          740150  BartonLLC  B1-69924   

                     quantity  unit price  ext price  
date                                                  
2014-01-01 04:21:00        39       86.69    3380.91  
2014-01-01 04:21:30        -1       63.16     -63.16  
2014-01-01 05:22:00        23       90.70    2086.10  
2014-01-01 06:22:30        41       21.05     863.05

In [106]:
type(mask)

pandas.core.frame.DataFrame

In [107]:
mask.columns

Index(['Unnamed: 0', 'account number', 'name', 'sku', 'quantity', 'unit price',
       'ext price'],
      dtype='object')

In [122]:
np.arange(9.0).reshape((3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [123]:
np.arange(3.0)

array([0., 1., 2.])

In [23]:
z = np.array(["4", "6", "14", "2"])

In [24]:
z1 = 10 * np.round(z.astype(np.float)/10)

In [25]:
z1

array([ 0., 10., 10.,  0.])