In [1]:
import pandas as pd

In [2]:
import os

In [3]:
import glob

In [4]:
import fnmatch

In [5]:
import json

In [6]:
import codecs

In [7]:
import datetime

In [8]:
import numpy as np

In [215]:
import geopy as gp

In [7]:
path = '/Users/smuel/AndroidStudioProjects/Louie7APKs/test-22-4/json-files/Init/'
listOfFiles = os.listdir(path)
for entry in listOfFiles:
    if not fnmatch.fnmatch(entry, '*.json'):
        listOfFiles.remove(entry)

In [10]:
#with open(path+listOfFiles[0]) as initRawData:
#    rawData = json.load(initRawData)

In [20]:
rawData = json.load(codecs.open(path+listOfFiles[0], 'r', 'utf-8-sig' ))

In [22]:
df_contect = pd.json_normalize(rawData, record_path=['Contact'])

In [23]:
df_contect

CONTACT_NAME  \
0  481B94E674CE906EC9F55A39AD957C386F180108   
1  35CC6A03E1D127213EC81FC9C089B58C21D7A216   
2  7CC169143411323FC14C492E13DE5EAD73C0DAB6   
3  E009DEC9156865BD4869565B3272A6E95AD3AF9D   
4  7CC169143411323FC14C492E13DE5EAD73C0DAB6   

                             CONTACT_NUMBER  
0  D02D42B32E2F76FB22D480A9A785F7173C69FC93  
1  4C41CB2AC0B572C3059599FD4868EA74AA9FDC3B  
2  44C930D75A6CCE9C05A0DEABB7BBF17E6D149972  
3  A55D80F98D860402DC4DDF056E2448AC0F034218  
4  403CF6CE507A8792C2ED5A9B16B0E626F06BCFB4

In [24]:
df_callogs = pd.json_normalize(rawData, record_path=['CallLogs'])

In [25]:
df_callogs

CALL_DURATION CALL_DATE_TIME CALL_TYPE  \
0              0     05-04-2021  OUTGOING   
1             13     10-10-2018  INCOMING   
2              0     10-10-2018  OUTGOING   

                                CALL_NUMBER  
0  42075D71F8E4E53970DD402AF9721DCD9B553DAA  
1  11DF13621D1880389D27523F4C624DE76E4B5DCA  
2  04D5D26AD6CB56FC30D1ECE2393DE2A3D1D385C2

In [26]:
df_gallery = pd.json_normalize(rawData, record_path=['ImgMetaData'])

In [27]:
df_gallery

IMAGE_TYPE  IMAGE_DATE_TIME
0   image/png       1475654217
1   image/png       1475654217
2  image/jpeg       1476026177
3  image/jpeg       1475654181

In [28]:
df_applist = pd.json_normalize(rawData, record_path=['InstallApps'])

In [29]:
df_applist

INSTALL_DATETIME APP_CATEGORY   APP_VARIANT
0     1480756438782       Others          Free
1     1519193104591       Social          Free
2     1530338067896         Game          Free
3     1520277074320       Social  Paid Feature

In [31]:
path

'/Users/smuel/AndroidStudioProjects/Louie7APKs/test-22-4/json-files/Init/'

In [32]:
listOfFiles

['ab71cf90-7909-414d-aafa-80a95ba9fa29_22-04-2021_19-29-08.json']

In [34]:
pathc = '/Users/smuel/AndroidStudioProjects/Louie7APKs/test-22-4/json-files/Continuous/'
listOfContFiles = os.listdir(pathc)
for entry in listOfContFiles:
    if not fnmatch.fnmatch(entry, '*.json'):
        listOfContFiles.remove(entry)

In [35]:
listOfContFiles

['ab71cf90-7909-414d-aafa-80a95ba9fa29_22-04-2021_19-30-18.json',
 'ab71cf90-7909-414d-aafa-80a95ba9fa29_22-04-2021_20-02-41.json']

In [36]:
setOfUsers = set(map(lambda x : x.split('_')[0], listOfContFiles))

In [37]:
setOfUsers

{'ab71cf90-7909-414d-aafa-80a95ba9fa29'}

In [41]:
dfs = []
for user in setOfUsers:
    userFiles = list(filter(lambda x : x.startswith(user), listOfContFiles))
    for f in userFiles:
        dt = f.split('_')[1]
        rawData = json.load(codecs.open(pathc+f, 'r', 'utf-8-sig' ))
        activeApps = pd.json_normalize(rawData["ActiveAppSamplingInfo"], record_path=['ActiveApps'])
        activeApps['ActiveAppSamplingTime'] = dt + " " + activeApps['ActiveAppSamplingTime']
        dfs.append(activeApps)
user_df = pd.concat(dfs)
print(user_df)

  ActiveAppSamplingTime  APP_CATEGORY
0              19:29:25  Productivity
1              19:29:25        Social
2              19:29:25        Social
3              19:29:45        Others
4              19:29:45        Others
5              19:29:45          Game
6              19:29:45          Maps
  ActiveAppSamplingTime  APP_CATEGORY
0   22-04-2021 19:29:25  Productivity
1   22-04-2021 19:29:25        Social
2   22-04-2021 19:29:25        Social
3   22-04-2021 19:29:45        Others
4   22-04-2021 19:29:45        Others
5   22-04-2021 19:29:45          Game
6   22-04-2021 19:29:45          Maps
  ActiveAppSamplingTime  APP_CATEGORY
0              20:02:06        Others
1              20:02:06        Others
2              20:02:26  Productivity
3              20:02:26        Others
4              20:02:26        Social
  ActiveAppSamplingTime  APP_CATEGORY
0   22-04-2021 20:02:06        Others
1   22-04-2021 20:02:06        Others
2   22-04-2021 20:02:26  Productivity
3   22-04-20

ActiveAppSamplingTime  APP_CATEGORY
0   22-04-2021 19:29:25  Productivity
1   22-04-2021 19:29:25        Social
2   22-04-2021 19:29:25        Social
3   22-04-2021 19:29:45        Others
4   22-04-2021 19:29:45        Others
5   22-04-2021 19:29:45          Game
6   22-04-2021 19:29:45          Maps
0   22-04-2021 20:02:06        Others
1   22-04-2021 20:02:06        Others
2   22-04-2021 20:02:26  Productivity
3   22-04-2021 20:02:26        Others
4   22-04-2021 20:02:26        Social

In [46]:
new_dt

['22', '04', '2021']

In [48]:
str1 = new_dt[2]+'-'+new_dt[1]+'-'+new_dt[0]+ ' ' + tm

In [49]:
str1

'2021-04-22 19:29:25'

In [50]:
dt_obj = datetime.datetime.strptime(str1, '%Y-%m-%d %H:%M:%S')

In [51]:
dt_obj

datetime.datetime(2021, 4, 22, 19, 29, 25)

In [52]:
print(dt_obj)

2021-04-22 19:29:25


In [62]:
dfs = []
for user in setOfUsers:
    userFiles = list(filter(lambda x : x.startswith(user), listOfContFiles))
    for f in userFiles:
        dt = f.split('_')[1]
        rawData = json.load(codecs.open(pathc+f, 'r', 'utf-8-sig' ))
        activeApps = pd.json_normalize(rawData["ActiveAppSamplingInfo"], record_path=['ActiveApps'])
        dt = dt.split('-')
        dt_obj = new_dt[2]+'-'+new_dt[1]+'-'+new_dt[0]
        activeApps['ActiveAppSamplingTime'] = dt_obj + ' ' + activeApps['ActiveAppSamplingTime']
        activeApps['ActiveAppSamplingTime'] = pd.to_datetime(activeApps['ActiveAppSamplingTime'], format='%Y-%m-%d %H:%M:%S') 
        dfs.append(activeApps)
user_df = pd.concat(dfs)
print(user_df)

  ActiveAppSamplingTime  APP_CATEGORY
0   2021-04-22 19:29:25  Productivity
1   2021-04-22 19:29:25        Social
2   2021-04-22 19:29:25        Social
3   2021-04-22 19:29:45        Others
4   2021-04-22 19:29:45        Others
5   2021-04-22 19:29:45          Game
6   2021-04-22 19:29:45          Maps
0   2021-04-22 20:02:06        Others
1   2021-04-22 20:02:06        Others
2   2021-04-22 20:02:26  Productivity
3   2021-04-22 20:02:26        Others
4   2021-04-22 20:02:26        Social


In [64]:
dfs = []
for user in setOfUsers:
    userFiles = list(filter(lambda x : x.startswith(user), listOfContFiles))
    for f in userFiles:
        dt = f.split('_')[1]
        rawData = json.load(codecs.open(pathc+f, 'r', 'utf-8-sig' ))
        activeApps = pd.json_normalize(rawData["ActiveAppSamplingInfo"], record_path=['ActiveApps'])
        dt = datetime.datetime.strptime(dt, '%d-%m-%Y').strftime('%Y-%m-%d')
        activeApps['ActiveAppSamplingTime'] = dt + ' ' + activeApps['ActiveAppSamplingTime']
        activeApps['ActiveAppSamplingTime'] = pd.to_datetime(activeApps['ActiveAppSamplingTime'], format='%Y-%m-%d %H:%M:%S') 
        dfs.append(activeApps)
user_df = pd.concat(dfs)
print(user_df)

  ActiveAppSamplingTime  APP_CATEGORY
0   2021-04-22 19:29:25  Productivity
1   2021-04-22 19:29:25        Social
2   2021-04-22 19:29:25        Social
3   2021-04-22 19:29:45        Others
4   2021-04-22 19:29:45        Others
5   2021-04-22 19:29:45          Game
6   2021-04-22 19:29:45          Maps
0   2021-04-22 20:02:06        Others
1   2021-04-22 20:02:06        Others
2   2021-04-22 20:02:26  Productivity
3   2021-04-22 20:02:26        Others
4   2021-04-22 20:02:26        Social


In [65]:
def listOfJsonFiles(path):
    listOfFiles = os.listdir(path)
    for entry in listOfFiles:
        if not fnmatch.fnmatch(entry, '*.json'):
            listOfFiles.remove(entry)
    return listOfFiles
fileLst = listOfJsonFiles(path)

In [66]:
fileLst

['ab71cf90-7909-414d-aafa-80a95ba9fa29_22-04-2021_19-29-08.json']

In [67]:
def createDfFromRaw(path, fname, field, ts_field):
    rawData = json.load(codecs.open(path + fname, 'r', 'utf-8-sig'))
    df = pd.json_normalize(rawData, record_path=[field])
    df[ts_field] = pd.to_datetime(df[ts_field], unit='s')
    return df
df0 = createDfFromRaw(path, fileLst[0], 'ImgMetaData', 'IMAGE_DATE_TIME')

In [68]:
print(df0)

   IMAGE_TYPE     IMAGE_DATE_TIME
0   image/png 2016-10-05 07:56:57
1   image/png 2016-10-05 07:56:57
2  image/jpeg 2016-10-09 15:16:17
3  image/jpeg 2016-10-05 07:56:21


In [69]:
df1 = createDfFromRaw(path, fileLst[0], 'InstallApps', 'INSTALL_DATETIME')

In [70]:
print(df1)

               INSTALL_DATETIME APP_CATEGORY   APP_VARIANT
0 2016-12-03 09:13:58.782000128       Others          Free
1 2018-02-21 06:05:04.591000064       Social          Free
2 2018-06-30 05:54:27.896000000         Game          Free
3 2018-03-05 19:11:14.320000000       Social  Paid Feature


In [81]:
def setAllUsersId(listOfContMetaDataFiles):
    setOfUsersId = set(map(lambda x: x.split('_')[0], listOfContMetaDataFiles))
    return setOfUsersId

def contDfByFiled(userId, path, listOfContMetaDataFiles, field, datetime_field):
    dfs = []
    userIdFiles = list(filter(lambda x : x.startswith(userId), listOfContMetaDataFiles))
    for uid in userIdFiles:
        d = uid.split('_')[1] # extract date
        rawData = json.load(codecs.open(path + uid, 'r', 'utf-8-sig'))
        if field == 'ActiveApps':
            df = pd.json_normalize(rawData["ActiveAppSamplingInfo"], record_path=['ActiveApps'])
        else:
            df = pd.json_normalize(rawData, record_path=[field])
        # update datetime field in df with ISO 8601
        date_obj = datetime.datetime.strptime(d, '%d-%m-%Y').strftime('%Y-%m-%d')
        df[datetime_field] = date_obj +  ' ' + df[datetime_field]
        df[datetime_field] = pd.to_datetime(df[datetime_field], format='%Y-%m-%d %H:%M:%S')
        dfs.append(df)
    return pd.concat(dfs)

fileLst1 = listOfJsonFiles(pathc)

In [72]:
fileLst1

['ab71cf90-7909-414d-aafa-80a95ba9fa29_22-04-2021_19-30-18.json',
 'ab71cf90-7909-414d-aafa-80a95ba9fa29_22-04-2021_20-02-41.json']

In [73]:
userId = setAllUsersId(fileLst1)

In [76]:
userId

{'ab71cf90-7909-414d-aafa-80a95ba9fa29'}

In [82]:
for uid in userId:
    df2 = contDfByFiled(uid, pathc, fileLst1, 'ScreenInfo', 'Sampling_Collect_Time')

In [83]:
print(df2)

   Screen_On Sampling_Collect_Time
0       True   2021-04-22 19:29:25
1       True   2021-04-22 19:29:40
2       True   2021-04-22 19:29:55
3       True   2021-04-22 19:30:10
0       True   2021-04-22 20:02:05
1       True   2021-04-22 20:02:20
2       True   2021-04-22 20:02:35


In [87]:
pip install xlrd

     |████████████████████████████████| 96 kB 451 kB/s eta 0:00:01
You should consider upgrading via the '/Users/smuel/Developer/Python/Louie7Predictors/venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [89]:
pip install openpyxl


     |████████████████████████████████| 243 kB 1.0 MB/s eta 0:00:01
You should consider upgrading via the '/Users/smuel/Developer/Python/Louie7Predictors/venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [253]:
df = pd.read_excel('/Users/smuel/Developer/Python/Louie7Predictors/sample-salesv3.xlsx')
df["date"] = pd.to_datetime(df['date'])

In [254]:
df.head()

account number                         name       sku  quantity  \
0          740150                   Barton LLC  B1-20000        39   
1          714466              Trantow-Barrows  S2-77896        -1   
2          218895                    Kulas Inc  B1-69924        23   
3          307599  Kassulke, Ondricka and Metz  S1-65481        41   
4          412290                Jerde-Hilpert  S2-34077         6   

   unit price  ext price                date  
0       86.69    3380.91 2014-01-01 07:21:51  
1       63.16     -63.16 2014-01-01 10:00:47  
2       90.70    2086.10 2014-01-01 13:24:58  
3       21.05     863.05 2014-01-01 15:05:22  
4       83.21     499.26 2014-01-01 23:26:55

In [260]:
df1= df.groupby(['name', pd.Grouper(key='date', freq='M')]).agg({'name' : ['count']})

In [262]:
df1.head(10)

name
                      count
name       date            
Barton LLC 2014-01-31     8
           2014-02-28     7
           2014-03-31     3
           2014-04-30    10
           2014-05-31     8
           2014-06-30     8
           2014-07-31     4
           2014-08-31    12
           2014-09-30     8
           2014-10-31     7

In [263]:
type(df1)

pandas.core.frame.DataFrame

In [265]:
df1 = df1.groupby(level=0).agg((np.mean, np.std))

In [364]:
df1.head(5)

name          
                                    count          
                                     mean       std
name                                               
Barton LLC                       6.833333  2.823065
Cronin, Oberbrunner and Spencer  5.583333  2.466441
Frami, Hills and Schmidt         6.000000  1.809068
Fritsch, Russel and Anderson     6.750000  2.800162
Halvorson, Crona and Champlin    4.833333  1.403459

In [270]:
 l = df1.loc['Halvorson': ].iloc[0].to_numpy()

In [271]:
l

array([4.83333333, 1.40345893])

In [275]:
r = df1.index.values

In [276]:
if 'lalala' in r :
    print(l)
else :
    print(np.zeros(2))

[0. 0.]


In [273]:
l1

array([6.08333333, 2.19330939])

In [169]:
df = df.loc[df['name'] == 'Barton LLC']

In [170]:
df.head()

account number        name       sku  quantity  unit price  ext price  \
0           740150  Barton LLC  B1-20000        39       86.69    3380.91   
85          740150  Barton LLC  B1-50809         8       19.60     156.80   
91          740150  Barton LLC  B1-53102         1       68.06      68.06   
96          740150  Barton LLC  S2-16558         2       90.91     181.82   
99          740150  Barton LLC  B1-86481        20       30.41     608.20   

                  date  cat  
0  2014-01-01 07:21:51    1  
85 2014-01-20 01:48:47    1  
91 2014-01-20 13:27:52    1  
96 2014-01-21 21:21:01    1  
99 2014-01-22 16:33:51    1

In [178]:
ds2 = df.groupby(pd.Grouper(key='date', freq='M'))['name'].count()

In [179]:
type(ds2)

pandas.core.series.Series

In [180]:
ds2.head(30)

date
2014-01-31    134
2014-02-28    108
2014-03-31    142
2014-04-30    134
2014-05-31    132
2014-06-30    128
2014-07-31    128
2014-08-31    117
2014-09-30    118
2014-10-31    126
2014-11-30    114
2014-12-31    119
Freq: M, Name: name, dtype: int64

In [181]:
ret = ds2.agg((np.mean, np.std)).to_numpy()

In [182]:
type(ret)

numpy.ndarray

In [183]:
ret

array([125.        ,   9.89949494])

In [259]:
ret[0]

125.0

In [312]:
df['deltaT'] = (df['date'] - df['date'].shift()).fillna(pd.Timedelta('0 days'))

In [313]:
df

account number                          name       sku  quantity  \
0             740150                    Barton LLC  B1-20000        39   
1             714466               Trantow-Barrows  S2-77896        -1   
2             218895                     Kulas Inc  B1-69924        23   
3             307599   Kassulke, Ondricka and Metz  S1-65481        41   
4             412290                 Jerde-Hilpert  S2-34077         6   
...              ...                           ...       ...       ...   
1495          737550  Fritsch, Russel and Anderson  S1-06532        12   
1496          786968      Frami, Hills and Schmidt  S1-06532        37   
1497          239344                    Stokes LLC  S2-10342        14   
1498          642753                   Pollich LLC  S2-82423         3   
1499          383080                      Will LLC  S2-00301        38   

      unit price  ext price                date  cat          deltaT  
0          86.69    3380.91 2014-01-01 07:21:51    1 0 days 00:00:00  
1          63.16     -63.16 2014-01-01 10:00:47    1 0 days 02:38:56  
2          90.70    2086.10 2014-01-01 13:24:58    1 0 days 03:24:11  
3          21.05     863.05 2014-01-01 15:05:22    1 0 days 01:40:24  
4          83.21     499.26 2014-01-01 23:26:55    1 0 days 08:21:33  
...          ...        ...                 ...  ...             ...  
1495       55.80     669.60 2014-12-30 13:38:13    1 0 days 00:59:48  
1496       13.14     486.18 2014-12-30 21:42:17    1 0 days 08:04:04  
1497       38.75     542.50 2014-12-30 22:45:19    1 0 days 01:03:02  
1498       65.97     197.91 2014-12-31 10:36:24    1 0 days 11:51:05  
1499       46.44    1764.72 2014-12-31 12:48:35    1 0 days 02:12:11  

[1500 rows x 9 columns]

In [305]:
df['deltaT'] = pd.to_timedelta(df['deltaT'].dt.total_seconds().astype(float))

In [314]:
df['deltaT'] = pd.to_timedelta(df['deltaT']).dt.total_seconds()

In [317]:
df.to_csv('sample_salesv3.csv')

In [34]:
ndf = pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
ndf['date'] = pd.to_datetime(ndf['date'])

In [36]:
ndf['norm'] = ndf.deltaT.apply(lambda x : 0 if x < 4000 else 1)

In [37]:
ndf['sub_group'] = ndf['norm'].cumsum()

In [40]:
df_acc= 2.0 * ndf.groupby('sub_group').apply(lambda x : x.shape[0])

In [41]:
df_acc.head(20)

sub_group
0      8.0
1      2.0
2     12.0
3     18.0
4     12.0
5     46.0
6      6.0
7     22.0
8     32.0
9     16.0
10     2.0
11    16.0
dtype: float64

In [32]:
type(df_acc)

pandas.core.series.Series

In [42]:
df_a = ndf.groupby('sub_group').apply(lambda x : x.shape[0])

In [43]:
df_a.head(20)

sub_group
0      4
1      1
2      6
3      9
4      6
5     23
6      3
7     11
8     16
9      8
10     1
11     8
dtype: int64

In [44]:
ndf.head()

Unnamed: 0  account number                         name       sku  \
0           0          740150                   Barton LLC  B1-20000   
1           1          714466              Trantow-Barrows  S2-77896   
2           2          218895                    Kulas Inc  B1-69924   
3           3          307599  Kassulke, Ondricka and Metz  S1-65481   
4           4          412290                Jerde-Hilpert  S2-34077   

   quantity  unit price  ext price                date  cat   deltaT  norm  \
0        39       86.69    3380.91 2014-01-01 07:21:51    1      0.0     0   
1        -1       63.16     -63.16 2014-01-01 10:00:47    1    536.0     0   
2        23       90.70    2086.10 2014-01-01 13:24:58    1   2251.0     0   
3        41       21.05     863.05 2014-01-01 15:05:22    1   2024.0     0   
4         6       83.21     499.26 2014-01-01 23:26:55    1  30093.0     1   

   sub_group  
0          0  
1          0  
2          0  
3          0  
4          1

In [46]:
df0 = ndf.groupby('name')

In [48]:
type(df0)

pandas.core.groupby.generic.DataFrameGroupBy

In [52]:
df1 = ndf.loc[ndf['name'] == 'Trantow-Barrows']

In [53]:
type(df1)

pandas.core.frame.DataFrame

In [54]:
df1.head()

Unnamed: 0  account number             name       sku  quantity  \
1            1          714466  Trantow-Barrows  S2-77896        -1   
5            5          714466  Trantow-Barrows  S2-77896        17   
8            8          714466  Trantow-Barrows  S1-50961        22   
23          23          714466  Trantow-Barrows  S1-30248        -1   
28          28          714466  Trantow-Barrows  B1-38851         4   

    unit price  ext price                date  cat   deltaT  norm  sub_group  
1        63.16     -63.16 2014-01-01 10:00:47    1    536.0     0          0  
5        87.63    1489.71 2014-01-02 10:07:15    1  38420.0     1          2  
8        84.09    1849.98 2014-01-03 11:29:02    1   2811.0     0          2  
23       16.97     -16.97 2014-01-06 18:27:28    1   2219.0     0          4  
28       60.04     240.16 2014-01-08 11:50:18    1   2610.0     0          5

In [55]:
df_a.to_numpy()

array([ 4,  1,  6,  9,  6, 23,  3, 11, 16,  8,  1,  8])

In [73]:
df4.head(5)

name
Barton LLC                                         [30, 30, 30]
Cronin, Oberbrunner and Spencer                            [30]
Frami, Hills and Schmidt                   [30, 30, 30, 30, 30]
Fritsch, Russel and Anderson       [30, 30, 30, 30, 30, 30, 30]
Halvorson, Crona and Champlin                      [30, 30, 30]
dtype: object

In [58]:
type(df4)

pandas.core.series.Series

In [60]:
df = pd.read_excel('/Users/smuel/Developer/Python/Louie7Predictors/sample-salesv3.xlsx')
df['date'] = pd.to_datetime(df['date'])

In [63]:
df['deltaT'] = (df['date'] - df['date'].shift()).fillna(pd.Timedelta('0 days'))

In [65]:
df['deltaT'] = pd.to_timedelta(df['deltaT']).dt.total_seconds()

In [67]:
df['Dur'] = df.deltaT.apply(lambda x : 0 if x <= 10000 else 1)
df['Dur'] = df.Dur.cumsum()

In [82]:
df0 = 30 * df.groupby('Dur').apply(lambda x : (df['name'], x.shape[0]))

In [83]:
type(df0)

pandas.core.series.Series

In [9]:
dfx =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
dfx['date'] = pd.to_datetime(dfx['date'])

In [10]:
dfx.head(5)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0           0          740150  BartonLLC  B1-20000        39       86.69   
1           1          714466  BartonLLC  S2-77896        -1       63.16   
2           2          218895  BartonLLC  B1-69924        23       90.70   
3           3          307599  BartonLLC  S1-65481        41       21.05   
4           4          412290   Kassulke  S2-34077         6       83.21   

   ext price                date  
0    3380.91 2014-01-01 07:21:00  
1     -63.16 2014-01-01 07:21:30  
2    2086.10 2014-01-01 07:22:00  
3     863.05 2014-01-01 07:22:30  
4     499.26 2014-01-01 07:23:00

In [225]:
df0 = dfx.loc[dfx['name'] == 'BartonLLC']

In [228]:
df0['deltaT'] = (df0['date'] - df0['date'].shift()).fillna(pd.Timedelta('0 days'))

In [229]:
df0['deltaT'] = pd.to_timedelta(df0['deltaT']).dt.total_seconds()

In [230]:
df0['dur'] = df0.deltaT.apply(lambda x : 1 if x > 31.0 else 0)

In [231]:
df0['dur'] = df0.dur.cumsum()

In [379]:
df0.head(10)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0            0          740150  BartonLLC  B1-20000        39       86.69   
1            1          714466  BartonLLC  S2-77896        -1       63.16   
2            2          218895  BartonLLC  B1-69924        23       90.70   
3            3          307599  BartonLLC  S1-65481        41       21.05   
29          29          729833  BartonLLC  B1-86481         6       81.79   
30          30          642753  BartonLLC  S1-93683         4       87.18   
31          31          714466  BartonLLC  B1-33087        32       19.56   
32          32          737550  BartonLLC  S1-27722        20       29.54   
33          33          218895  BartonLLC  S1-06532         3       22.36   
34          34          307599  BartonLLC  S2-78676        35       33.04   

    ext price                date             dur          deltaT  
0     3380.91 2014-01-01 07:21:00 0 days 00:00:00 0 days 00:00:00  
1      -63.16 2014-01-01 07:21:30 0 days 00:00:30 0 days 00:00:30  
2     2086.10 2014-01-01 07:22:00 0 days 00:00:30 0 days 00:00:30  
3      863.05 2014-01-01 07:22:30 0 days 00:00:30 0 days 00:00:30  
29     490.74 2014-01-01 07:35:30 0 days 00:13:00 0 days 00:13:00  
30     348.72 2014-01-01 07:36:00 0 days 00:00:30 0 days 00:00:30  
31     625.92 2014-01-01 07:36:30 0 days 00:00:30 0 days 00:00:30  
32     590.80 2014-01-01 07:37:00 0 days 00:00:30 0 days 00:00:30  
33      67.08 2014-01-01 07:37:30 0 days 00:00:30 0 days 00:00:30  
34    1156.40 2014-01-01 07:38:00 0 days 00:00:30 0 days 00:00:30

In [233]:
ar = 10 * df0.groupby('dur').apply(lambda x : x.shape[0]).to_numpy()

In [234]:
ar

array([40, 80])

In [11]:
df0['deltaT'] = (df0['date'] - df0['date'].shift()).fillna(pd.Timedelta('0 days'))

In [13]:
dfx['deltaT'] = pd.to_timedelta(dfx['deltaT']).dt.total_seconds()

In [15]:
dfx['dur'] = dfx.deltaT.apply(lambda x : 1 if x > 31.0 else 0)

In [17]:
dfx['dur'] = dfx.dur.cumsum()

In [380]:
dfx.head(10)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0           0          740150  BartonLLC  B1-20000        39       86.69   
1           1          714466  BartonLLC  S2-77896        -1       63.16   
2           2          218895  BartonLLC  B1-69924        23       90.70   
3           3          307599  BartonLLC  S1-65481        41       21.05   
4           4          412290   Kassulke  S2-34077         6       83.21   
5           5          714466   KulasInc  S2-77896        17       87.63   
6           6          218895   KulasInc  B1-65551         2       31.10   
7           7          729833   KulasInc  S1-30248         8       33.25   
8           8          714466   KulasInc  S1-50961        22       84.09   
9           9          737550   KulasInc  S2-82423        14       81.92   

   ext price                date  deltaT  dur  
0    3380.91 2014-01-01 07:21:00     0.0    0  
1     -63.16 2014-01-01 07:21:30    30.0    0  
2    2086.10 2014-01-01 07:22:00    30.0    0  
3     863.05 2014-01-01 07:22:30    30.0    0  
4     499.26 2014-01-01 07:23:00    30.0    0  
5    1489.71 2014-01-01 07:23:30    30.0    0  
6      62.20 2014-01-01 07:24:00    30.0    0  
7     266.00 2014-01-01 07:24:30    30.0    0  
8    1849.98 2014-01-01 07:25:00    30.0    0  
9    1146.88 2014-01-01 07:25:30    30.0    0

In [36]:
np_list = dfx.groupby('name').apply(lambda x : x.groupby('dur').apply(lambda y : 10 * y.shape[0]).to_numpy())

In [37]:
np_list

name
BartonLLC       [120]
Fritsch          [30]
Kassulke         [10]
KeelingLLC       [90]
KulasInc        [100]
WhiteTrantow     [60]
dtype: object

In [38]:
type(np_list)

pandas.core.series.Series

In [35]:
np_list.columns

Int64Index([0], dtype='int64', name='dur')

In [39]:
np_list.to_dict()

{'BartonLLC': array([120]),
 'Fritsch': array([30]),
 'Kassulke': array([10]),
 'KeelingLLC': array([90]),
 'KulasInc': array([100]),
 'WhiteTrantow': array([60])}

In [53]:
def dfWithDur(df):
    # add column of time diff between 2 consecutive rows measure time delta in seconds.
    X = (df['date'] - df['date'].shift()).fillna(pd.Timedelta('0 days'))
    Y =  pd.to_timedelta(X).dt.total_seconds()
    res =  1 if Y > (30+1) else 0
    return res

In [54]:
dfy =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
dfy['date'] = pd.to_datetime(dfy['date'])
df0 = dfy.loc[dfy['name'] == 'BartonLLC']

In [57]:
df0

Unnamed: 0  account number       name       sku  quantity  unit price  \
0            0          740150  BartonLLC  B1-20000        39       86.69   
1            1          714466  BartonLLC  S2-77896        -1       63.16   
2            2          218895  BartonLLC  B1-69924        23       90.70   
3            3          307599  BartonLLC  S1-65481        41       21.05   
29          29          729833  BartonLLC  B1-86481         6       81.79   
30          30          642753  BartonLLC  S1-93683         4       87.18   
31          31          714466  BartonLLC  B1-33087        32       19.56   
32          32          737550  BartonLLC  S1-27722        20       29.54   
33          33          218895  BartonLLC  S1-06532         3       22.36   
34          34          307599  BartonLLC  S2-78676        35       33.04   
35          35          527099  BartonLLC  S1-27722        48       43.40   
36          36          218895  BartonLLC  S2-34077        16       73.04   

    ext price                date  
0     3380.91 2014-01-01 07:21:00  
1      -63.16 2014-01-01 07:21:30  
2     2086.10 2014-01-01 07:22:00  
3      863.05 2014-01-01 07:22:30  
29     490.74 2014-01-01 07:35:30  
30     348.72 2014-01-01 07:36:00  
31     625.92 2014-01-01 07:36:30  
32     590.80 2014-01-01 07:37:00  
33      67.08 2014-01-01 07:37:30  
34    1156.40 2014-01-01 07:38:00  
35    2083.20 2014-01-01 07:38:30  
36    1168.64 2014-01-01 07:39:00

In [80]:
dfy['dur'] = dfy['date'].diff().apply(lambda x: x/np.timedelta64(1, 's')).fillna(0).astype('int64').apply(lambda x: 1 if x > 31 else 0)

In [104]:
dfy =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
dfy['date'] = pd.to_datetime(dfy['date'])
dfy = dfy.loc[dfy['name'] == 'BartonLLC']

In [106]:
dfy = dfy.loc[dfy['name'] == 'BartonLLC']

In [107]:
dfy.head(10)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0            0          740150  BartonLLC  B1-20000        39       86.69   
1            1          714466  BartonLLC  S2-77896        -1       63.16   
2            2          218895  BartonLLC  B1-69924        23       90.70   
3            3          307599  BartonLLC  S1-65481        41       21.05   
29          29          729833  BartonLLC  B1-86481         6       81.79   
30          30          642753  BartonLLC  S1-93683         4       87.18   
31          31          714466  BartonLLC  B1-33087        32       19.56   
32          32          737550  BartonLLC  S1-27722        20       29.54   
33          33          218895  BartonLLC  S1-06532         3       22.36   
34          34          307599  BartonLLC  S2-78676        35       33.04   

    ext price                date  
0     3380.91 2014-01-01 07:21:00  
1      -63.16 2014-01-01 07:21:30  
2     2086.10 2014-01-01 07:22:00  
3      863.05 2014-01-01 07:22:30  
29     490.74 2014-01-01 07:35:30  
30     348.72 2014-01-01 07:36:00  
31     625.92 2014-01-01 07:36:30  
32     590.80 2014-01-01 07:37:00  
33      67.08 2014-01-01 07:37:30  
34    1156.40 2014-01-01 07:38:00

In [108]:
dfy['dur'] = dfy['date'].diff().apply(lambda x: x/np.timedelta64(1, 's')).fillna(0).astype('int64').apply(lambda x: 1 if x > 31 else 0)

In [110]:
dfy['dur'] = dfy.dur.cumsum()

In [184]:
dfy.head(10)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0            0          740150  BartonLLC  B1-20000        39       86.69   
1            1          714466  BartonLLC  S2-77896        -1       63.16   
2            2          218895  BartonLLC  B1-69924        23       90.70   
3            3          307599  BartonLLC  S1-65481        41       21.05   
29          29          729833  BartonLLC  B1-86481         6       81.79   
30          30          642753  BartonLLC  S1-93683         4       87.18   
31          31          714466  BartonLLC  B1-33087        32       19.56   
32          32          737550  BartonLLC  S1-27722        20       29.54   
33          33          218895  BartonLLC  S1-06532         3       22.36   
34          34          307599  BartonLLC  S2-78676        35       33.04   

    ext price                date  dur  
0     3380.91 2014-01-01 07:21:00    0  
1      -63.16 2014-01-01 07:21:30    0  
2     2086.10 2014-01-01 07:22:00    0  
3      863.05 2014-01-01 07:22:30    0  
29     490.74 2014-01-01 07:35:30    1  
30     348.72 2014-01-01 07:36:00    1  
31     625.92 2014-01-01 07:36:30    1  
32     590.80 2014-01-01 07:37:00    1  
33      67.08 2014-01-01 07:37:30    1  
34    1156.40 2014-01-01 07:38:00    1

In [185]:
np_list =  dfy.groupby('dur').apply(lambda x : x.shape[0])

In [381]:
np_list.head(5)

dur
0    40
1    80
dtype: int64

In [199]:
dfy['daily'] = (dfy['date']).dt.date

In [200]:
dfzz =  dfy.groupby('daily').apply(lambda y : y.groupby('dur').apply(lambda x : x.shape[0]))

In [186]:
np_list.head(10)

dur
0    40
1    80
dtype: int64

In [144]:
np_list.size

2

In [198]:
(dfy['date']).dt.date

0     2014-01-01
1     2014-01-01
2     2014-01-01
3     2014-01-01
29    2014-01-01
30    2014-01-01
31    2014-01-01
32    2014-01-01
33    2014-01-01
34    2014-01-01
35    2014-01-01
36    2014-01-01
Name: date, dtype: object

In [201]:
dfzz.head(10)

dur         0  1
daily           
2014-01-01  4  8

In [202]:
type(dfzz)

pandas.core.frame.DataFrame

In [205]:
dfzz.to_dict()

{0: {datetime.date(2014, 1, 1): 4}, 1: {datetime.date(2014, 1, 1): 8}}

In [206]:
np_list

dur
0    40
1    80
dtype: int64

In [207]:
type(np_list)

pandas.core.series.Series

In [209]:
x = np_list.to_numpy()

In [210]:
y = np_list.to_numpy()

In [213]:
c = np.empty((x.size + y.size,), dtype=x.dtype)
c[0::2] = x
c[1::2] = y

In [214]:
c

array([40, 40, 80, 80])

In [216]:
from geopy.geocoders import Nominatim

In [222]:
geolocator = Nominatim(user_agent='smuel')

In [238]:
location = geolocator.reverse([32.0875634, 34.7854761], exactly_one=True, language='en')

In [239]:
location.address

'Gimnasia hertzliya/Jabotinsky, Jabotinsky, Tel Aviv, The New North, Tel Aviv-Yafo, Tel Aviv Subdistrict, Tel Aviv District, no, Israel'

In [347]:
address = location.raw['address'].get('country')

In [348]:
address

'Israel'

In [249]:
dfy['daily'] = pd.to_datetime(dfy['daily'])

In [250]:
dfy['daily'].dt.day_name()

0     Wednesday
1     Wednesday
2     Wednesday
3     Wednesday
29    Wednesday
30    Wednesday
31    Wednesday
32    Wednesday
33    Wednesday
34    Wednesday
35    Wednesday
36    Wednesday
Name: daily, dtype: object

In [252]:
pd.to_datetime(dfy['daily']).dt.day_name()

0     Wednesday
1     Wednesday
2     Wednesday
3     Wednesday
29    Wednesday
30    Wednesday
31    Wednesday
32    Wednesday
33    Wednesday
34    Wednesday
35    Wednesday
36    Wednesday
Name: daily, dtype: object

In [277]:
Boxes = {'Color': ['Green','Green','Green','Blue','Blue','Red','Red','Red'],
         'Shape': ['Rectangle','Rectangle','Square','Rectangle','Square','Square','Square','Rectangle']
        }

dfe = pd.DataFrame(Boxes, columns= ['Color','Shape'])

In [278]:
dups = dfe.pivot_table(index=['Color','Shape'], aggfunc='size')

In [279]:
type(dups)

pandas.core.series.Series

In [280]:
dups

Color  Shape    
Blue   Rectangle    1
       Square       1
Green  Rectangle    2
       Square       1
Red    Rectangle    1
       Square       2
dtype: int64

In [290]:
shape = dups.groupby(level=0).agg((np.mean, np.std))

In [291]:
type(shape)

pandas.core.frame.DataFrame

In [292]:
shape

mean       std
Color                
Blue    1.0  0.000000
Green   1.5  0.707107
Red     1.5  0.707107

In [285]:
dfd =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
dfd['date'] = pd.to_datetime(dfd['date'])

In [287]:
dfd.tail()

Unnamed: 0  account number       name       sku  quantity  unit price  \
36          36          218895  BartonLLC  S2-34077        16       73.04   
37          37          383080   KulasInc  S2-23246        23       59.98   
38          38          383080   KulasInc  B1-05914        25       98.46   
39          39          729833   KulasInc  B1-33364         7       10.87   
40          40          714466   KulasInc  B1-65551        48       69.36   

    ext price                date  
36    1168.64 2014-01-02 07:39:00  
37    1379.54 2014-01-02 07:39:30  
38    2461.50 2014-01-02 07:40:00  
39      76.09 2014-01-02 07:40:30  
40    3329.28 2014-01-02 07:41:00

In [288]:
dsd = dfd.groupby(pd.Grouper(key='date', freq='D')).apply(lambda x : x.pivot_table(index=['name'], aggfunc='size'))

In [289]:
dsd

date        name        
2014-01-01  BartonLLC       4
            Kassulke        1
            KeelingLLC      9
            KulasInc        6
            WhiteTrantow    5
2014-01-02  BartonLLC       8
            Fritsch         3
            KulasInc        4
            WhiteTrantow    1
dtype: int64

In [297]:
npl = dsd.groupby(level=0).agg(np.mean).to_numpy()

In [298]:
npl

array([5, 4])

In [299]:
np.mean(npl)

4.5

In [300]:
dfd =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
dfd['date'] = pd.to_datetime(dfd['date'])

In [301]:
dss = dfd.groupby(['name', pd.Grouper(key='date', freq='D')]).apply(lambda x : x.pivot_table(index=['sku'], aggfunc='size'))

In [302]:
dss

name          date        sku     
BartonLLC     2014-01-01  B1-20000    1
                          B1-69924    2
                          S2-77896    1
              2014-01-02  B1-86481    6
                          S1-27722    2
Fritsch       2014-01-02  B1-38851    1
                          B1-53636    1
                          S2-83881    1
Kassulke      2014-01-01  S2-34077    1
KeelingLLC    2014-01-01  S1-06532    1
                          S1-30248    4
                          S2-00301    1
                          S2-23246    3
KulasInc      2014-01-01  S1-50961    3
                          S2-34077    3
              2014-01-02  B1-05914    3
                          S2-23246    1
WhiteTrantow  2014-01-01  S2-00301    4
                          S2-83881    1
              2014-01-02  S2-83881    1
dtype: int64

In [303]:
type(dss)

pandas.core.series.Series

In [316]:
dff = dss.groupby(level=0).apply(lambda x : x.groupby('date').agg(np.mean))

In [317]:
dff

name          date      
BartonLLC     2014-01-01    1.333333
              2014-01-02    4.000000
Fritsch       2014-01-02    1.000000
Kassulke      2014-01-01    1.000000
KeelingLLC    2014-01-01    2.250000
KulasInc      2014-01-01    3.000000
              2014-01-02    2.000000
WhiteTrantow  2014-01-01    2.500000
              2014-01-02    1.000000
dtype: float64

In [312]:
type(dff)

pandas.core.series.Series

In [334]:
dff.groupby(level=0).apply(lambda x : (np.mean(x), np.std(x)))

name
BartonLLC       (2.6666666666666665, 1.3333333333333335)
Fritsch                                       (1.0, 0.0)
Kassulke                                      (1.0, 0.0)
KeelingLLC                                   (2.25, 0.0)
KulasInc                                      (2.5, 0.5)
WhiteTrantow                                (1.75, 0.75)
dtype: object

In [335]:
dfz = dff.groupby(level=0).apply(lambda x : (np.mean(x), np.std(x)))

In [337]:
type(dfz)

pandas.core.series.Series

In [338]:
dfz.loc['WhiteTrantow' : ].iloc[0]

(1.75, 0.75)

In [340]:
dfd['quantity'].to_numpy()

array([39, -1, 23, 41,  6, 17,  2,  8, 22, 14, 15,  7,  6, 17, 23, 34, 14,
       14, 10, 33, 45, 24,  2, -1, 34,  5, 42, 42,  4,  6,  4, 32, 20,  3,
       35, 48, 16, 23, 25,  7, 48])

In [345]:
dfy['day'] = pd.to_datetime((dfy['date']).dt.date).dt.day_name()

In [355]:
dfd.head(5)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0           0          740150  BartonLLC  B1-20000        39       86.69   
1           1          714466  BartonLLC  S2-77896        -1       63.16   
2           2          218895  BartonLLC  B1-69924        23       90.70   
3           3          307599  BartonLLC  B1-69924        41       21.05   
4           4          412290   Kassulke  S2-34077         6       83.21   

   ext price                date  
0    3380.91 2014-01-01 07:21:00  
1     -63.16 2014-01-01 07:21:30  
2    2086.10 2014-01-01 07:22:00  
3     863.05 2014-01-01 07:22:30  
4     499.26 2014-01-01 07:23:00

In [357]:
dn = df.groupby('name').agg({'name' : ['count']})

In [358]:
type(dn)

pandas.core.frame.DataFrame

In [359]:
dn

name
                                count
name                                 
Barton LLC                         82
Cronin, Oberbrunner and Spencer    67
Frami, Hills and Schmidt           72
Fritsch, Russel and Anderson       81
Halvorson, Crona and Champlin      58
Herman LLC                         62
Jerde-Hilpert                      89
Kassulke, Ondricka and Metz        64
Keeling LLC                        74
Kiehn-Spinka                       79
Koepp Ltd                          82
Kuhn-Gusikowski                    73
Kulas Inc                          94
Pollich LLC                        73
Purdy-Kunde                        53
Sanford and Sons                   71
Stokes LLC                         72
Trantow-Barrows                    94
White-Trantow                      86
Will LLC                           74

In [378]:
dn.loc['Trantow-Barrows': ].iloc[0].to_numpy()

array([94])

In [387]:
ts = "1594568007.937"
f = pd.to_numeric(ts, downcast="float")
t = pd.to_datetime(f, unit='s')
print(t)

2020-07-12 15:34:24


In [407]:
df2 =  pd.read_csv('/Users/smuel/Developer/Python/Louie7Predictors/sample_salesv3.csv')
df2['date'] = pd.to_datetime(dfd['date'])

In [408]:
df2.head(5)

Unnamed: 0  account number       name       sku  quantity  unit price  \
0           0          740150  BartonLLC  B1-20000        39       86.69   
1           1          714466  BartonLLC  S2-77896        -1       63.16   
2           2          218895  BartonLLC  B1-69924        23       90.70   
3           3          307599  BartonLLC  B1-69924        41       21.05   
4           4          412290   Kassulke  S2-34077         6       83.21   

   ext price                date  
0    3380.91 2014-01-01 07:21:00  
1     -63.16 2014-01-01 07:21:30  
2    2086.10 2014-01-01 07:22:00  
3     863.05 2014-01-01 07:22:30  
4     499.26 2014-01-01 07:23:00

In [391]:
ds = df1.groupby(pd.Grouper(key='date', freq='D'))['quantity'].apply(lambda x: x.to_numpy())

In [392]:
ds

date
2014-01-01    [39, -1, 23, 41, 6, 17, 2, 8, 22, 14, 15, 7, 6...
2014-01-02    [5, 42, 42, 4, 6, 4, 32, 20, 3, 35, 48, 16, 23...
Freq: D, Name: quantity, dtype: object

In [393]:
type(ds)

pandas.core.series.Series

In [394]:
ds.size

2

In [395]:
ds.shape

(2,)

In [396]:
mrx = ds.to_numpy()

In [397]:
mrx

array([array([39, -1, 23, 41,  6, 17,  2,  8, 22, 14, 15,  7,  6, 17, 23, 34, 14,
       14, 10, 33, 45, 24,  2, -1, 34]),
       array([ 5, 42, 42,  4,  6,  4, 32, 20,  3, 35, 48, 16, 23, 25,  7, 48])],
      dtype=object)

In [400]:
mrx[1].size

16

In [402]:
mrx[0].size

25